
import { NoteDefinition, ChordExtensionType, Language, GuitarVoicing } from './types';

export const NOTES: NoteDefinition[] = [
  { name: 'C', latinName: 'Do', index: 0 },
  { name: 'C#', latinName: 'Do#', index: 1 },
  { name: 'D', latinName: 'Re', index: 2 },
  { name: 'D#', latinName: 'Re#', index: 3 },
  { name: 'E', latinName: 'Mi', index: 4 },
  { name: 'F', latinName: 'Fa', index: 5 },
  { name: 'F#', latinName: 'Fa#', index: 6 },
  { name: 'G', latinName: 'Sol', index: 7 },
  { name: 'G#', latinName: 'Sol#', index: 8 },
  { name: 'A', latinName: 'La', index: 9 },
  { name: 'A#', latinName: 'La#', index: 10 },
  { name: 'B', latinName: 'Si', index: 11 },
];

export const QUALITIES: Record<string, number[]> = {
  major: [0, 4, 7],
  minor: [0, 3, 7],
};

export const EXTENSIONS: Record<ChordExtensionType, { name: string, intervals: (base: number[]) => number[] }> = {
  'none': { 
    name: '', 
    intervals: (base) => base 
  },
  '7': { 
    name: '7', 
    intervals: (base) => [...base, 10] 
  },
  'maj7': { 
    name: 'maj7', 
    intervals: (base) => [...base, 11] 
  },
  '9': { 
    name: '9', 
    intervals: (base) => [...base, 10, 14] // Dom7 + 9
  },
  'add9': {
    name: 'add9',
    intervals: (base) => [...base, 14] // Triad + 9 (No 7th)
  },
  'maj9': {
    name: 'maj9', 
    intervals: (base) => [...base, 11, 14] // Maj7 + 9
  },
  'sus2': { 
    name: 'sus2', 
    intervals: (base) => [base[0], 2, base[2]] 
  },
  'sus4': { 
    name: 'sus4', 
    intervals: (base) => [base[0], 5, base[2]] 
  },
  '7sus4': {
    name: '7sus4',
    intervals: () => [0, 5, 7, 10] // Root, 4, 5, b7 (Overrides base)
  },
  '6': {
    name: '6',
    intervals: (base) => [...base, 9]
  },
  'dim': { 
    name: 'dim', 
    intervals: () => [0, 3, 6] 
  },
  'aug': { 
    name: 'aug', 
    intervals: () => [0, 4, 8] 
  },
  'm7b5': {
    name: 'm7b5',
    intervals: () => [0, 3, 6, 10] // Root, b3, b5, b7 (Overrides base to dim triad + min7)
  },
  'maj7#11': {
    name: 'maj7#11',
    intervals: (base) => [...base, 11, 18] // Base(Maj), 7, #11
  },
  'maj13': {
    name: 'maj13',
    intervals: (base) => [...base, 11, 21] // Base(Maj), 7, 13
  }
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: "Armonix",
    appSubtitle: "Piano & Guitar Chord Visualizer",
    modeVisualizer: "Visualizer",
    modeComposer: "Song Composer",
    modeDetector: "Chord Detector",
    modeGroovebox: "Groovebox",
    root: "Fundamental / Root",
    quality: "Quality",
    extension: "Variation",
    aiInsight: "Additional Information",
    play: "Play",
    stop: "Stop",
    loading: "Loading...",
    notation: "Notation",
    major: "Major",
    minor: "Minor",
    basic: "Basic",
    noInsight: "No insight available.",
    apiKeyError: "API Key not configured.",
    aboutTitle: "What is Armonix?",
    aboutText1: "I'm Francisco Carle, musician and creator of Armonix. While teaching piano for popular music, I realized that visualizing how chords are constructed on the keyboard is often a significant barrier for students.",
    aboutText2: "Armonix was born to bridge that gap. It serves as an interactive visual aid to demystify chord formation. Even for experienced musicians, theory can sometimes slip our minds—Armonix is your always-available companion for those moments.",
    dedication: "I dedicate this web app to Celeste, Helena, Matteo, and Gaspar, our musicians of the future.",
    instrument: "Instrument",
    piano: "Piano",
    guitar: "Guitar",
    close: "Close",
    guitarNoVoicing: "Voicing unavailable in first 5 frets.",
    footerText: "Armonix v 1.1 is an application developed with the good energy of",
    composerTitle: "Song Composer",
    composerSubtitle: "Generate chord progressions based on your style.",
    lblStyle: "Style",
    lblMood: "Mood",
    lblTempo: "Tempo",
    lblComplexity: "Complexity",
    btnCompose: "Compose Song",
    keyOf: "Key",
    composerResult: "Result",
    mood_happy: "Happy",
    mood_sad: "Sad",
    mood_melancholic: "Melancholic",
    mood_energetic: "Energetic",
    mood_relaxed: "Relaxed",
    mood_epic: "Epic",
    mood_meditation: "Meditation",
    mood_concentration: "Concentration",
    tempo_slow: "Slow",
    tempo_moderate: "Moderate",
    tempo_fast: "Fast",
    complexity_basic: "Basic",
    complexity_intermediate: "Intermediate",
    complexity_advanced: "Advanced",
    // Detector
    detectorTitle: "Chord Detector",
    detectorSubtitle: "Select at least 3 keys on the piano to identify the chord.",
    clearKeys: "Clear Keys",
    detecting: "Detecting...",
    chordDetected: "Detected Chord",
    selectMoreKeys: "Select at least 3 keys...",
    unknownChord: "Unknown Chord",
    // Groovebox
    grooveTitle: "Groovebox",
    grooveSubtitle: "Create beats and basslines with the built-in engine.",
    bpm: "BPM",
    kick: "Kick",
    snare: "Snare",
    hihat: "Hi-Hat",
    clap: "Clap",
    bass: "Bass (Acid)",
    clearPattern: "Clear Pattern",
    randomize: "Randomize",
    groovePitch: "Pitch",
    grooveInstruction: "Select a step above • Press key to assign pitch",
  },
  es: {
    appTitle: "Armonix",
    appSubtitle: "Visualizador de Acordes",
    modeVisualizer: "Visualizador",
    modeComposer: "Compositor",
    modeDetector: "Detector",
    modeGroovebox: "Groovebox",
    root: "Nota Fundamental",
    quality: "Cualidad",
    extension: "Variación / Tensión",
    aiInsight: "Información Adicional",
    play: "Tocar",
    stop: "Parar",
    loading: "Cargando...",
    notation: "Notación",
    major: "Mayor",
    minor: "Menor",
    basic: "Básico",
    noInsight: "No hay información disponible.",
    apiKeyError: "Llave API no configurada.",
    aboutTitle: "¿Qué es Armonix?",
    aboutText1: "Soy Francisco Carle, músico y creador de Armonix. Cuando me ha tocado explicar las bases de la interpretación en el piano para música popular, me encuentro con la barrera de entrada de que entender cómo se forman los acordes en el piano es un proceso que cuesta explicar.",
    aboutText2: "Armonix nace como un apoyo visual para mostrar gráficamente cómo se forman los acordes. Aunque sepamos la teoría, a veces se nos puede olvidar, y este es una especie de recordatorio para formar acordes cuando sea que lo necesites.",
    dedication: "Dedico esta app web a Celeste, Helena, Matteo y Gaspar, nuestros músicos del futuro.",
    instrument: "Instrumento",
    piano: "Piano",
    guitar: "Guitarra",
    close: "Cerrar",
    guitarNoVoicing: "Posición no disponible en los primeros 5 trastes.",
    footerText: "Armonix v 1.1 es una aplicación desarrollada con la buena energía de",
    composerTitle: "Compositor de Canciones",
    composerSubtitle: "Genera progresiones de acordes basadas en tu estilo.",
    lblStyle: "Estilo",
    lblMood: "Ánimo",
    lblTempo: "Velocidad",
    lblComplexity: "Complejidad",
    btnCompose: "Componer Canción",
    keyOf: "Tonalidad",
    composerResult: "Resultado",
    mood_happy: "Feliz",
    mood_sad: "Triste",
    mood_melancholic: "Melancólico",
    mood_energetic: "Enérgico",
    mood_relaxed: "Relajado",
    mood_epic: "Épico",
    mood_meditation: "Meditación",
    mood_concentration: "Concentración",
    tempo_slow: "Lento",
    tempo_moderate: "Moderado",
    tempo_fast: "Rápido",
    complexity_basic: "Básico",
    complexity_intermediate: "Intermedio",
    complexity_advanced: "Avanzado",
    // Detector
    detectorTitle: "Detector de Acordes",
    detectorSubtitle: "Selecciona al menos 3 teclas en el piano para identificar el acorde.",
    clearKeys: "Limpiar Teclas",
    detecting: "Detectando...",
    chordDetected: "Acorde Detectado",
    selectMoreKeys: "Selecciona al menos 3 teclas...",
    unknownChord: "Acorde Desconocido",
    // Groovebox
    grooveTitle: "Groovebox",
    grooveSubtitle: "Crea ritmos y bajos con el motor integrado.",
    bpm: "BPM",
    kick: "Bombo",
    snare: "Caja",
    hihat: "Hi-Hat",
    clap: "Palmas",
    bass: "Bajo (Acid)",
    clearPattern: "Limpiar Patrón",
    randomize: "Aleatorio",
    groovePitch: "Tono",
    grooveInstruction: "Selecciona un paso arriba • Presiona tecla para asignar tono",
  },
  it: {
    appTitle: "Armonix",
    appSubtitle: "Visualizzatore di Accordi per Piano e Chitarra",
    modeVisualizer: "Visualizzatore",
    modeComposer: "Compositore",
    modeDetector: "Rilevatore",
    modeGroovebox: "Groovebox",
    root: "Fondamentale / Tonica",
    quality: "Qualità",
    extension: "Variazione",
    aiInsight: "Informazioni Aggiuntive",
    play: "Suona",
    stop: "Stop",
    loading: "Caricamento...",
    notation: "Notazione",
    major: "Maggiore",
    minor: "Minore",
    basic: "Base",
    noInsight: "Nessuna informazione disponibile.",
    apiKeyError: "Chiave API non configurata.",
    aboutTitle: "Cos'è Armonix?",
    aboutText1: "Sono Francisco Carle, musicista e creatore di Armonix. Insegnando pianoforte, ho capito che visualizzare la costruzione degli accordi è spesso un ostacolo per gli studenti.",
    aboutText2: "Armonix nasce per colmare questo divario. Serve come aiuto visivo interattivo per demistificare la formazione degli accordi.",
    dedication: "Dedico questa web app a Celeste, Helena, Matteo e Gaspar, i nostri musicisti del futuro.",
    instrument: "Strumento",
    piano: "Pianoforte",
    guitar: "Chitarra",
    close: "Chiudi",
    guitarNoVoicing: "Posizione non disponibile nei primi 5 tasti.",
    footerText: "Armonix v 1.1 è un'applicazione sviluppata con la buona energia di",
    composerTitle: "Compositore di Canzoni",
    composerSubtitle: "Genera progressioni di accordi basate sul tuo stile.",
    lblStyle: "Stile",
    lblMood: "Umore",
    lblTempo: "Tempo",
    lblComplexity: "Complessità",
    btnCompose: "Componi Canzone",
    keyOf: "Tonalità",
    composerResult: "Risultato",
    mood_happy: "Felice",
    mood_sad: "Triste",
    mood_melancholic: "Malinconico",
    mood_energetic: "Energico",
    mood_relaxed: "Rilassato",
    mood_epic: "Epico",
    mood_meditation: "Meditazione",
    mood_concentration: "Concentrazione",
    tempo_slow: "Lento",
    tempo_moderate: "Moderato",
    tempo_fast: "Veloce",
    complexity_basic: "Base",
    complexity_intermediate: "Intermedio",
    complexity_advanced: "Avanzato",
    // Detector
    detectorTitle: "Rilevatore di Accordi",
    detectorSubtitle: "Seleziona almeno 3 tasti sul pianoforte per identificare l'accordo.",
    clearKeys: "Pulisci Tasti",
    detecting: "Rilevamento...",
    chordDetected: "Accordo Rilevato",
    selectMoreKeys: "Seleziona almeno 3 tasti...",
    unknownChord: "Accordo Sconosciuto",
    // Groovebox
    grooveTitle: "Groovebox",
    grooveSubtitle: "Crea ritmi e bassi con il motore integrato.",
    bpm: "BPM",
    kick: "Cassa",
    snare: "Rullante",
    hihat: "Hi-Hat",
    clap: "Clap",
    bass: "Basso (Acid)",
    clearPattern: "Pulisci Pattern",
    randomize: "Casuale",
    groovePitch: "Tono",
    grooveInstruction: "Seleziona un passo sopra • Premi un tasto per assegnare il tono",
  },
  fr: {
    appTitle: "Armonix",
    appSubtitle: "Visualiseur d'Accords Piano & Guitare",
    modeVisualizer: "Visualiseur",
    modeComposer: "Compositeur",
    modeDetector: "Détecteur",
    modeGroovebox: "Groovebox",
    root: "Fondamentale",
    quality: "Qualité",
    extension: "Variation",
    aiInsight: "Informations Supplémentaires",
    play: "Jouer",
    stop: "Arrêter",
    loading: "Chargement...",
    notation: "Notation",
    major: "Majeur",
    minor: "Mineur",
    basic: "Basique",
    noInsight: "Aucune information disponible.",
    apiKeyError: "Clé API non configurée.",
    aboutTitle: "Qu'est-ce qu'Armonix ?",
    aboutText1: "Je suis Francisco Carle, musicien et créateur d'Armonix. En enseignant le piano, j'ai réalisé que visualiser la construction des accords est souvent un obstacle pour les étudiants.",
    aboutText2: "Armonix est né pour combler cette lacune. Il sert d'aide visuelle interactive pour démystifier la formation des accords.",
    dedication: "Je dédie cette application web à Celeste, Helena, Matteo et Gaspar, nos musiciens du futur.",
    instrument: "Instrument",
    piano: "Piano",
    guitar: "Guitare",
    close: "Fermer",
    guitarNoVoicing: "Position non disponible dans les 5 premières frettes.",
    footerText: "Armonix v 1.1 est une application développée avec la bonne énergie de",
    composerTitle: "Compositeur de Chansons",
    composerSubtitle: "Générez des progressions d'accords basées sur votre style.",
    lblStyle: "Style",
    lblMood: "Humeur",
    lblTempo: "Tempo",
    lblComplexity: "Complexité",
    btnCompose: "Composer",
    keyOf: "Tonalité",
    composerResult: "Résultat",
    mood_happy: "Joyeux",
    mood_sad: "Triste",
    mood_melancholic: "Mélancolique",
    mood_energetic: "Énergique",
    mood_relaxed: "Détendu",
    mood_epic: "Épique",
    mood_meditation: "Méditation",
    mood_concentration: "Concentration",
    tempo_slow: "Lent",
    tempo_moderate: "Modéré",
    tempo_fast: "Rapide",
    complexity_basic: "Basique",
    complexity_intermediate: "Intermédiaire",
    complexity_advanced: "Avancé",
    // Detector
    detectorTitle: "Détecteur d'Accords",
    detectorSubtitle: "Sélectionnez au moins 3 touches sur le piano pour identifier l'accord.",
    clearKeys: "Effacer les touches",
    detecting: "Détection...",
    chordDetected: "Accord Détecté",
    selectMoreKeys: "Sélectionnez au moins 3 touches...",
    unknownChord: "Accord Inconnu",
    // Groovebox
    grooveTitle: "Groovebox",
    grooveSubtitle: "Créez des rythmes et des basses avec le moteur intégré.",
    bpm: "BPM",
    kick: "Grosse Caisse",
    snare: "Caisse Claire",
    hihat: "Hi-Hat",
    clap: "Clap",
    bass: "Basse (Acid)",
    clearPattern: "Effacer le motif",
    randomize: "Aléatoire",
    groovePitch: "Hauteur",
    grooveInstruction: "Sélectionnez une étape ci-dessus • Appuyez sur une touche",
  },
  de: {
    appTitle: "Armonix",
    appSubtitle: "Klavier & Gitarren Akkord-Visualisierer",
    modeVisualizer: "Visualisierer",
    modeComposer: "Komponist",
    modeDetector: "Detektor",
    modeGroovebox: "Groovebox",
    root: "Grundton",
    quality: "Qualität",
    extension: "Variation",
    aiInsight: "Zusätzliche Informationen",
    play: "Abspielen",
    stop: "Stoppen",
    loading: "Laden...",
    notation: "Notation",
    major: "Dur",
    minor: "Moll",
    basic: "Basis",
    noInsight: "Keine Informationen verfügbar.",
    apiKeyError: "API-Schlüssel nicht konfiguriert.",
    aboutTitle: "Was ist Armonix?",
    aboutText1: "Ich bin Francisco Carle, Musiker und Schöpfer von Armonix. Beim Klavierunterricht habe ich festgestellt, dass die Visualisierung von Akkorden oft ein Hindernis für Schüler darstellt.",
    aboutText2: "Armonix wurde geschaffen, um diese Lücke zu schließen. Es dient als interaktive visuelle Hilfe, um die Akkordbildung zu entmystifizieren.",
    dedication: "Ich widme diese Web-App Celeste, Helena, Matteo und Gaspar, unseren Musikern der Zukunft.",
    instrument: "Instrument",
    piano: "Klavier",
    guitar: "Gitarre",
    close: "Schließen",
    guitarNoVoicing: "Keine Griffweise in den ersten 5 Bünden verfügbar.",
    footerText: "Armonix v 1.1 ist eine Anwendung, die mit der guten Energie von",
    composerTitle: "Song-Komponist",
    composerSubtitle: "Generiere Akkordfolgen basierend auf deinem Stil.",
    lblStyle: "Stil",
    lblMood: "Stimmung",
    lblTempo: "Tempo",
    lblComplexity: "Komplexität",
    btnCompose: "Komponieren",
    keyOf: "Tonart",
    composerResult: "Ergebnis",
    mood_happy: "Glücklich",
    mood_sad: "Traurig",
    mood_melancholic: "Melancholisch",
    mood_energetic: "Energetisch",
    mood_relaxed: "Entspannt",
    mood_epic: "Episch",
    mood_meditation: "Meditation",
    mood_concentration: "Konzentration",
    tempo_slow: "Langsam",
    tempo_moderate: "Mittel",
    tempo_fast: "Schnell",
    complexity_basic: "Basis",
    complexity_intermediate: "Mittel",
    complexity_advanced: "Fortgeschritten",
    // Detector
    detectorTitle: "Akkord-Detektor",
    detectorSubtitle: "Wähle mindestens 3 Tasten auf dem Klavier, um den Akkord zu identifizieren.",
    clearKeys: "Tasten Löschen",
    detecting: "Erkennen...",
    chordDetected: "Erkannter Akkord",
    selectMoreKeys: "Wähle mindestens 3 Tasten...",
    unknownChord: "Unbekannter Akkord",
    // Groovebox
    grooveTitle: "Groovebox",
    grooveSubtitle: "Erstelle Beats und Basslines mit der integrierten Engine.",
    bpm: "BPM",
    kick: "Kick",
    snare: "Snare",
    hihat: "Hi-Hat",
    clap: "Clap",
    bass: "Bass (Acid)",
    clearPattern: "Muster löschen",
    randomize: "Zufällig",
    groovePitch: "Tonhöhe",
    grooveInstruction: "Wähle oben einen Schritt • Drücke Taste für Tonhöhe",
  },
  zh: {
    appTitle: "Armonix",
    appSubtitle: "钢琴和吉他和弦可视化工具",
    modeVisualizer: "可视化工具",
    modeComposer: "歌曲创作者",
    modeDetector: "和弦识别器",
    modeGroovebox: "Groovebox",
    root: "根音",
    quality: "性质",
    extension: "变奏",
    aiInsight: "附加信息",
    play: "播放",
    stop: "停止",
    loading: "加载中...",
    notation: "记谱法",
    major: "大调",
    minor: "小调",
    basic: "基础",
    noInsight: "无可用信息。",
    apiKeyError: "未配置API密钥。",
    aboutTitle: "什么是 Armonix？",
    aboutText1: "我是 Francisco Carle，音乐家和 Armonix 的创造者。在教授流行钢琴时，我意识到在键盘上可视化和弦结构通常是学生的一大障碍。",
    aboutText2: "Armonix 的诞生就是为了弥补这一差距。它作为一个交互式的视觉辅助工具，旨在揭开和弦构成的神秘面纱。",
    dedication: "我将这个网络应用程序献给 Celeste, Helena, Matteo 和 Gaspar，我们未来的音乐家。",
    instrument: "乐器",
    piano: "钢琴",
    guitar: "吉他",
    close: "关闭",
    guitarNoVoicing: "前5品无可用指法。",
    footerText: "Armonix v 1.1 是由以下良好能量开发的应用程序：",
    composerTitle: "歌曲创作者",
    composerSubtitle: "根据您的风格生成和弦进行。",
    lblStyle: "风格",
    lblMood: "情绪",
    lblTempo: "速度",
    lblComplexity: "复杂度",
    btnCompose: "创作歌曲",
    keyOf: "调性",
    composerResult: "结果",
    mood_happy: "快乐",
    mood_sad: "悲伤",
    mood_melancholic: "忧郁",
    mood_energetic: "充满活力",
    mood_relaxed: "放松",
    mood_epic: "史诗",
    mood_meditation: "冥想",
    mood_concentration: "专注",
    tempo_slow: "慢",
    tempo_moderate: "中",
    tempo_fast: "快",
    complexity_basic: "基础",
    complexity_intermediate: "中级",
    complexity_advanced: "高级",
    // Detector
    detectorTitle: "和弦识别器",
    detectorSubtitle: "在钢琴上至少选择3个键以识别和弦。",
    clearKeys: "清除按键",
    detecting: "检测中...",
    chordDetected: "检测到的和弦",
    selectMoreKeys: "请至少选择3个键...",
    unknownChord: "未知和弦",
    // Groovebox
    grooveTitle: "Groovebox",
    grooveSubtitle: "使用内置引擎创建节拍和贝斯线。",
    bpm: "BPM",
    kick: "底鼓",
    snare: "军鼓",
    hihat: "踩镲",
    clap: "拍手",
    bass: "贝斯 (Acid)",
    clearPattern: "清除模式",
    randomize: "随机",
    groovePitch: "音高",
    grooveInstruction: "选择上方的一个步骤 • 按键分配音高",
  },
  ja: {
    appTitle: "Armonix",
    appSubtitle: "ピアノ＆ギターコードビジュアライザー",
    modeVisualizer: "ビジュアライザー",
    modeComposer: "作曲ツール",
    modeDetector: "コード検出",
    modeGroovebox: "グルーヴボックス",
    root: "ルート音",
    quality: "クオリティ",
    extension: "バリエーション",
    aiInsight: "追加情報",
    play: "再生",
    stop: "停止",
    loading: "読み込み中...",
    notation: "表記",
    major: "メジャー",
    minor: "マイナー",
    basic: "基本",
    noInsight: "情報がありません。",
    apiKeyError: "APIキーが設定されていません。",
    aboutTitle: "Armonixとは？",
    aboutText1: "私はArmonixの開発者で音楽家のFrancisco Carleです。ポピュラー音楽のピアノを教える中で、鍵盤上でのコードの仕組みを視覚化することが生徒にとって大きな壁になっていることに気づきました。",
    aboutText2: "Armonixはそのギャップを埋めるために生まれました。コード形成を分かりやすくするためのインタラクティブな視覚補助ツールです。",
    dedication: "このウェブアプリを、未来の音楽家であるCeleste、Helena、Matteo、Gasparに捧げます。",
    instrument: "楽器",
    piano: "ピアノ",
    guitar: "ギター",
    close: "閉じる",
    guitarNoVoicing: "最初の5フレットで利用可能なボイシングがありません。",
    footerText: "Armonix v 1.1は、以下の良いエネルギーで開発されたアプリケーションです：",
    composerTitle: "ソングコンポーザー",
    composerSubtitle: "あなたのスタイルに基づいてコード進行を生成します。",
    lblStyle: "スタイル",
    lblMood: "ムード",
    lblTempo: "テンポ",
    lblComplexity: "複雑さ",
    btnCompose: "作曲する",
    keyOf: "キー",
    composerResult: "結果",
    mood_happy: "幸せ",
    mood_sad: "悲しい",
    mood_melancholic: "メランコリック",
    mood_energetic: "エネルギッシュ",
    mood_relaxed: "リラックス",
    mood_epic: "壮大",
    mood_meditation: "瞑想",
    mood_concentration: "集中",
    tempo_slow: "遅い",
    tempo_moderate: "普通",
    tempo_fast: "速い",
    complexity_basic: "基本",
    complexity_intermediate: "中級",
    complexity_advanced: "上級",
    // Detector
    detectorTitle: "コード検出器",
    detectorSubtitle: "ピアノ上のキーを3つ以上選択して、コードを特定してください。",
    clearKeys: "キーをクリア",
    detecting: "検出中...",
    chordDetected: "検出されたコード",
    selectMoreKeys: "3つ以上のキーを選択してください...",
    unknownChord: "不明なコード",
    // Groovebox
    grooveTitle: "グルーヴボックス",
    grooveSubtitle: "内蔵エンジンでビートとベースラインを作成します。",
    bpm: "BPM",
    kick: "キック",
    snare: "スネア",
    hihat: "ハイハット",
    clap: "クラップ",
    bass: "ベース (Acid)",
    clearPattern: "パターンをクリア",
    randomize: "ランダム",
    groovePitch: "ピッチ",
    grooveInstruction: "上のステップを選択 • キーを押してピッチを割り当て",
  },
  ko: {
    appTitle: "Armonix",
    appSubtitle: "피아노 및 기타 코드 시각화 도구",
    modeVisualizer: "시각화 도구",
    modeComposer: "작곡 도구",
    modeDetector: "코드 감지기",
    modeGroovebox: "그루브박스",
    root: "근음",
    quality: "코드 성질",
    extension: "변형",
    aiInsight: "추가 정보",
    play: "재생",
    stop: "정지",
    loading: "로딩 중...",
    notation: "표기법",
    major: "메이저",
    minor: "마이너",
    basic: "기본",
    noInsight: "정보 없음.",
    apiKeyError: "API 키가 설정되지 않았습니다.",
    aboutTitle: "Armonix란 무엇인가요?",
    aboutText1: "저는 음악가이자 Armonix의 창작자인 Francisco Carle입니다. 피아노를 가르치면서 학생들이 건반 위에서 코드가 어떻게 구성되는지 시각화하는 데 어려움을 겪는 것을 보았습니다.",
    aboutText2: "Armonix는 그 간극을 메우기 위해 탄생했습니다. 코드 형성을 쉽게 이해할 수 있도록 돕는 대화형 시각 보조 도구입니다.",
    dedication: "이 웹 앱을 미래의 음악가인 Celeste, Helena, Matteo, Gaspar에게 바칩니다.",
    instrument: "악기",
    piano: "피아노",
    guitar: "기타",
    close: "닫기",
    guitarNoVoicing: "처음 5프렛 내에서 가능한 보이싱이 없습니다.",
    footerText: "Armonix v 1.1는 다음의 좋은 에너지로 개발된 애플리케이션입니다:",
    composerTitle: "노래 작곡",
    composerSubtitle: "스타일에 따라 코드 진행을 생성하세요.",
    lblStyle: "스타일",
    lblMood: "분위기",
    lblTempo: "템포",
    lblComplexity: "복잡도",
    btnCompose: "작곡하기",
    keyOf: "조성",
    composerResult: "결과",
    mood_happy: "행복함",
    mood_sad: "슬픔",
    mood_melancholic: "우울함",
    mood_energetic: "활기참",
    mood_relaxed: "편안함",
    mood_epic: "웅장함",
    mood_meditation: "명상",
    mood_concentration: "집중",
    tempo_slow: "느림",
    tempo_moderate: "보통",
    tempo_fast: "빠름",
    complexity_basic: "기본",
    complexity_intermediate: "중급",
    complexity_advanced: "고급",
    // Detector
    detectorTitle: "코드 감지기",
    detectorSubtitle: "코드를 식별하려면 피아노에서 최소 3개의 키를 선택하세요.",
    clearKeys: "키 지우기",
    detecting: "감지 중...",
    chordDetected: "감지된 코드",
    selectMoreKeys: "최소 3개의 키를 선택하세요...",
    unknownChord: "알 수 없는 코드",
    // Groovebox
    grooveTitle: "그루브박스",
    grooveSubtitle: "내장 엔진으로 비트와 베이스 라인을 만드세요.",
    bpm: "BPM",
    kick: "킥",
    snare: "스네어",
    hihat: "하이햇",
    clap: "박수",
    bass: "베이스 (Acid)",
    clearPattern: "패턴 지우기",
    randomize: "무작위",
    groovePitch: "피치",
    grooveInstruction: "위의 단계를 선택하세요 • 키를 눌러 피치 할당",
  }
};

export const COMPOSER_OPTIONS = {
  styles: [
    'pop', 'rock', 'ballad', 'jazz', 'reggae', 'lofi', 
    'country', 'techno', 'electropop', 'alternative', 'heavy-metal', 'blues', 'k-pop', 'ost'
  ],
  moods: ['happy', 'sad', 'melancholic', 'energetic', 'relaxed', 'epic', 'meditation', 'concentration'],
  tempos: ['slow', 'moderate', 'fast'],
  complexities: ['basic', 'intermediate', 'advanced']
};

// Guitar Voicings (Standard Open Positions & Basic Variations for 5 frets)
type VoicingMap = Record<string, Record<string, Record<string, GuitarVoicing>>>;

export const GUITAR_VOICINGS: VoicingMap = {
  // C Roots
  'C': {
    'major': {
      'none': [-1, 3, 2, 0, 1, 0],
      '7':    [-1, 3, 2, 3, 1, 0],
      'maj7': [-1, 3, 2, 0, 0, 0],
      '9':    [-1, 3, 2, 0, 3, 0],
      'sus2': [-1, 3, 0, 0, 1, 0],
      'sus4': [-1, 3, 3, 0, 1, 1],
      '6':    [-1, 3, 2, 2, 1, 0],
      'dim':  [-1, 3, 4, 2, 4, -1],
      'aug':  [-1, 3, 2, 1, 1, 0],
    },
    'minor': {
      'none': [-1, 3, 5, 5, 4, 3],
      '7':    [-1, 3, 5, 3, 4, 3],
      'maj7': [-1, 3, 5, 4, 4, 3],
      '9':    [-1, 3, 1, 3, 3, -1],
      'sus2': [-1, 3, 5, 5, 3, 3],
      'sus4': [-1, 3, 5, 5, 6, 3],
      '6':    [-1, 3, 1, 2, 1, -1],
      'dim':  [-1, 3, 4, 2, 4, -1],
      'aug':  [-1, 3, 1, 0, 1, -1],
    }
  },
  // D Roots
  'D': {
    'major': {
      'none': [-1, -1, 0, 2, 3, 2],
      '7':    [-1, -1, 0, 2, 1, 2],
      'maj7': [-1, -1, 0, 2, 2, 2],
      '9':    [-1, -1, 0, 2, 1, 0],
      'sus2': [-1, -1, 0, 2, 3, 0],
      'sus4': [-1, -1, 0, 2, 3, 3],
      '6':    [-1, -1, 0, 2, 0, 2],
      'dim':  [-1, -1, 0, 1, 3, 1],
      'aug':  [-1, -1, 0, 3, 3, 2],
    },
    'minor': {
      'none': [-1, -1, 0, 2, 3, 1],
      '7':    [-1, -1, 0, 2, 1, 1],
      'maj7': [-1, -1, 0, 2, 2, 1],
      '9':    [-1, -1, 0, 2, 1, 0],
      'sus2': [-1, -1, 0, 2, 3, 0],
      'sus4': [-1, -1, 0, 2, 3, 3],
      '6':    [-1, -1, 0, 2, 0, 1],
      'dim':  [-1, -1, 0, 1, 3, 1],
      'aug':  [-1, -1, 0, 3, 3, 1],
    }
  },
  // E Roots
  'E': {
    'major': {
      'none': [0, 2, 2, 1, 0, 0],
      '7':    [0, 2, 0, 1, 0, 0],
      'maj7': [0, 2, 1, 1, 0, 0],
      '9':    [0, 2, 0, 1, 0, 2],
      'sus2': [0, 2, 4, 4, 0, 0],
      'sus4': [0, 2, 2, 2, 0, 0],
      '6':    [0, 2, 2, 1, 2, 0],
      'dim':  [0, 1, 2, 0, 2, 0],
      'aug':  [0, 3, 2, 1, 1, 0],
    },
    'minor': {
      'none': [0, 2, 2, 0, 0, 0],
      '7':    [0, 2, 0, 0, 0, 0],
      'maj7': [0, 2, 1, 0, 0, 0],
      '9':    [0, 2, 0, 0, 0, 2],
      'sus2': [0, 2, 4, 0, 0, 0],
      'sus4': [0, 2, 2, 2, 0, 0],
      '6':    [0, 2, 2, 0, 2, 0],
      'dim':  [0, 1, 2, 0, 2, 0],
      'aug':  [0, 2, 2, 0, 1, 0],
    }
  },
  // F Roots
  'F': {
    'major': {
      'none': [1, 3, 3, 2, 1, 1],
      '7':    [1, 3, 1, 2, 1, 1],
      'maj7': [-1, 3, 3, 2, 1, 0],
      '9':    [1, 3, 1, 2, 1, 3],
      'sus2': [-1, 3, 3, 0, 1, 1],
      'sus4': [1, 3, 3, 3, 1, 1],
      '6':    [1, 3, 3, 2, 3, 1],
      'dim':  [-1, -1, 0, 1, 0, 1],
      'aug':  [-1, 0, 3, 2, 2, 1],
    },
    'minor': {
      'none': [1, 3, 3, 1, 1, 1],
      '7':    [1, 3, 1, 1, 1, 1],
      'maj7': [1, 3, 2, 1, 1, 1],
      '9':    [1, 3, 1, 1, 1, 3],
      'sus2': [1, 3, 3, 0, 1, 1],
      'sus4': [1, 3, 3, 3, 1, 1],
      '6':    [1, 3, 3, 1, 3, 1],
      'dim':  [1, 2, 3, 1, 3, 1],
      'aug':  [1, 3, 3, 1, 2, 1],
    }
  },
  // G Roots
  'G': {
    'major': {
      'none': [3, 2, 0, 0, 0, 3],
      '7':    [3, 2, 0, 0, 0, 1],
      'maj7': [3, 2, 0, 0, 0, 2],
      '9':    [3, 2, 0, 2, 0, 3],
      'sus2': [3, 0, 0, 0, 3, 3],
      'sus4': [3, 3, 0, 0, 1, 3],
      '6':    [3, 2, 0, 0, 0, 0],
      'dim':  [3, 4, 5, 3, 5, 3],
      'aug':  [3, 2, 1, 0, 0, 3],
    },
    'minor': {
      'none': [3, 5, 5, 3, 3, 3],
      '7':    [3, 5, 3, 3, 3, 3],
      'maj7': [3, 5, 4, 3, 3, 3],
      '9':    [3, 5, 3, 3, 3, 5],
      'sus2': [3, 5, 5, 3, 3, 3],
      'sus4': [3, 5, 5, 5, 3, 3],
      '6':    [3, 5, 5, 3, 5, 3],
      'dim':  [3, 4, 5, 3, 5, 3],
      'aug':  [3, 5, 5, 3, 4, 3],
    }
  },
  // A Roots
  'A': {
    'major': {
      'none': [-1, 0, 2, 2, 2, 0],
      '7':    [-1, 0, 2, 0, 2, 0],
      'maj7': [-1, 0, 2, 1, 2, 0],
      '9':    [-1, 0, 2, 0, 0, 0],
      'sus2': [-1, 0, 2, 2, 0, 0],
      'sus4': [-1, 0, 2, 2, 3, 0],
      '6':    [-1, 0, 2, 2, 2, 2],
      'dim':  [-1, 0, 1, 2, 1, 2],
      'aug':  [-1, 0, 3, 2, 2, 1],
    },
    'minor': {
      'none': [-1, 0, 2, 2, 1, 0],
      '7':    [-1, 0, 2, 0, 1, 0],
      'maj7': [-1, 0, 2, 1, 1, 0],
      '9':    [-1, 0, 2, 0, 0, 0],
      'sus2': [-1, 0, 2, 2, 0, 0],
      'sus4': [-1, 0, 2, 2, 3, 0],
      '6':    [-1, 0, 2, 2, 1, 2],
      'dim':  [-1, 0, 1, 2, 1, 0],
      'aug':  [-1, 0, 2, 2, 1, 1],
    }
  },
  // B Roots
  'B': {
    'major': {
      'none': [-1, 2, 4, 4, 4, 2],
      '7':    [-1, 2, 1, 2, 0, 2],
      'maj7': [-1, 2, 4, 3, 4, 2],
      '9':    [-1, 2, 1, 2, 2, 2],
      'sus2': [-1, 2, 4, 4, 2, 2],
      'sus4': [-1, 2, 4, 4, 5, 2],
      '6':    [-1, 2, 4, 4, 4, 4],
      'dim':  [-1, 2, 3, 4, 3, -1],
      'aug':  [-1, 2, 1, 0, 0, 3],
    },
    'minor': {
      'none': [-1, 2, 4, 4, 3, 2],
      '7':    [-1, 2, 0, 2, 0, 2],
      'maj7': [-1, 2, 4, 3, 3, 2],
      '9':    [-1, 2, 0, 2, 2, 2],
      'sus2': [-1, 2, 4, 4, 2, 2],
      'sus4': [-1, 2, 4, 4, 5, 2],
      '6':    [-1, 2, 4, 4, 3, 4],
      'dim':  [-1, 2, 3, 4, 3, -1],
      'aug':  [-1, 2, 4, 4, 4, 3],
    }
  }
};
GUITAR_VOICINGS['A#'] = {
   'major': { 'none': [-1, 1, 3, 3, 3, 1], '7': [-1, 1, 3, 1, 3, 1], 'maj7': [-1, 1, 3, 2, 3, 1] },
   'minor': { 'none': [-1, 1, 3, 3, 2, 1], '7': [-1, 1, 3, 1, 2, 1], 'maj7': [-1, 1, 3, 2, 2, 1] }
};
GUITAR_VOICINGS['C#'] = {
   'major': { 'none': [-1, 4, 6, 6, 6, 4], '7': [-1, 4, 6, 4, 6, 4], 'maj7': [-1, 4, 6, 5, 6, 4] },
   'minor': { 'none': [-1, 4, 6, 6, 5, 4], '7': [-1, 4, 6, 4, 5, 4], 'maj7': [-1, 4, 6, 5, 5, 4] }
};
GUITAR_VOICINGS['D#'] = {
   'major': { 'none': [-1, 6, 8, 8, 8, 6], '7': [-1, 6, 8, 6, 8, 6] },
   'minor': { 'none': [-1, 6, 8, 8, 7, 6] }
};
GUITAR_VOICINGS['F#'] = {
   'major': { 'none': [2, 4, 4, 3, 2, 2], '7': [2, 4, 2, 3, 2, 2] },
   'minor': { 'none': [2, 4, 4, 2, 2, 2], '7': [2, 4, 2, 2, 2, 2] }
};
GUITAR_VOICINGS['G#'] = {
   'major': { 'none': [4, 6, 6, 5, 4, 4], '7': [4, 6, 4, 5, 4, 4] },
   'minor': { 'none': [4, 6, 6, 4, 4, 4], '7': [4, 6, 4, 4, 4, 4] }
};
